### ISSUE TITLE
Testing (and validation) time

### ISSUE THREAD

**Issue by pauhidalgoo** [caiselvas/language-identification#1]
## Issue Description
Testing right now is very slow, which makes it complex to evaluate the results of the parameters. It also limits us to the number of combinations that we can try.

## Problem
Each validation iteration and testing (10.000 sentences * 6 languages)  takes two minutes. The smoothing functions and probs_total seem to be fully optimized, using dictionaries (but there may be room for improvement).

## Solutions tried
Using a probabilities dictionary doesn't seem to make it faster (I have tried it, at least the way it is now). 

## Proposed solutions
Maybe trying to use Numpy or some library would make it faster. Also, if we can't find a better solution, we can always reduce the validation size (modify train.py).

**Comment by pauhidalgoo** [comment]
Update: the modifications made by @caiselvass seem to have improved the time in aprox. 25% (now it takes 1'30"). Great job!

**Comment by caiselvas** [comment]
Update: @pauhidalgoo found that the probabilities for the trigrams were calculated more times than needed, increasing a lot the execution time. Now they are calculated only once and the test takes only 8"!
